package codechicken.multipart.test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.lang.reflect.Proxy;
import java.util.BitSet;

import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.server.MinecraftServer;

import org.junit.jupiter.api.Test;

import codechicken.lib.data.MCDataInput;
import codechicken.lib.data.MCDataOutput;
import codechicken.lib.data.MCDataOutputWrapper;
import codechicken.microblock.FaceMicroClass$;
import codechicken.microblock.HollowMicroClass$;
import codechicken.microblock.Microblock;
import codechicken.microblock.MicroblockGenerator;
import codechicken.multipart.MultiPartRegistry;
import codechicken.multipart.TFacePart;
import codechicken.multipart.TMultiPart;
import codechicken.multipart.TileMultipart;
import codechicken.multipart.asm.MultipartMixinFactory;
import codechicken.multipart.scalatraits.TSlottedTile;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Loader;
import scala.collection.immutable.Nil$;

class ForgeEnvironmentSmokeTest {

    @Test
    void reachesServerStartedWithWorldAndMultipartModsLoaded() {
        assertTrue(ForgeMultipartFunctionalTestMod.preInitialized);
        assertTrue(ForgeMultipartFunctionalTestMod.initialized);
        assertTrue(ForgeMultipartFunctionalTestMod.postInitialized);
        assertTrue(ForgeMultipartFunctionalTestMod.serverAboutToStart);
        assertTrue(ForgeMultipartFunctionalTestMod.serverStarted);
        assertTrue(FMLCommonHandler.instance().getSide().isServer());
        assertTrue(Loader.isModLoaded("ForgeMultipart"));
        assertTrue(Loader.isModLoaded("ForgeMicroblock"));
        assertTrue(Loader.isModLoaded("McMultipart"));

        MinecraftServer server = MinecraftServer.getServer();
        assertNotNull(server);
        assertNotNull(server.worldServers);
        assertTrue(server.worldServers.length > 0);
        assertNotNull(server.worldServers[0]);
    }

    /**
     * Microblock classes are generated by ASM at runtime. TFacePart's members are now Java interface defaults rather
     * than Scala trait forwarders, so a generated class inherits them instead of declaring its own; this checks the JVM
     * resolves them for a class that never existed at compile time.
     */
    @Test
    void generatedMicroblockInheritsFacePartDefaults() {
        Microblock face = MicroblockGenerator.create(FaceMicroClass$.MODULE$, 0, false);
        Microblock hollow = MicroblockGenerator.create(HollowMicroClass$.MODULE$, 0, false);

        assertTrue(face instanceof TFacePart);
        assertEquals(0, ((TFacePart) face).redstoneConductionMap());

        // HollowMicroblock overrides both members, so its generated class must not pick up the defaults.
        assertTrue(hollow instanceof TFacePart);
        assertEquals(0x10, ((TFacePart) hollow).redstoneConductionMap());
        assertFalse(((TFacePart) hollow).solid(0));
    }

    /**
     * Part registration needs FML's active mod container, so none of this is reachable from a plain JVM test. Startup
     * exercises both overloads downstream depends on: Content registers through the deprecated IPartFactory array form,
     * and each microblock class registers through the IPartFactory2 varargs form.
     */
    @Test
    void registryResolvesPartsRegisteredThroughBothFactoryOverloads() throws Exception {
        assertTrue(MultiPartRegistry.loaded(), "Registration must be closed once the server has started");

        // mc_torch comes from the deprecated IPartFactory array overload.
        TMultiPart torch = MultiPartRegistry.loadPart("mc_torch", null);
        assertNotNull(torch);
        assertEquals("mc_torch", torch.getType());

        // mcr_face comes from the IPartFactory2 varargs overload. Its factory reads the tag, so it needs a real one;
        // an absent material name resolves to the missing-material placeholder rather than failing.
        TMultiPart face = MultiPartRegistry.loadPart("mcr_face", new NBTTagCompound());
        assertNotNull(face);
        assertEquals("mcr_face", face.getType());

        assertNotNull(MultiPartRegistry.getModContainer("mc_torch"));
        assertNotNull(MultiPartRegistry.getModContainer("mcr_face"));
    }

    @Test
    void partIdsRoundTripThroughTheRegistryCarrier() {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        MCDataOutput output = new MCDataOutputWrapper(new DataOutputStream(bytes));
        TMultiPart torch = MultiPartRegistry.loadPart("mc_torch", null);
        MultiPartRegistry.writePartID(output, torch);

        TMultiPart read = MultiPartRegistry.readPart(input(bytes.toByteArray()));

        assertNotNull(read);
        assertEquals("mc_torch", read.getType());
    }

    /** CodeChickenLib has no stream-backed MCDataInput, so the carrier reads are proxied. */
    private static MCDataInput input(byte[] bytes) {
        DataInputStream data = new DataInputStream(new ByteArrayInputStream(bytes));
        return (MCDataInput) Proxy.newProxyInstance(
                MCDataInput.class.getClassLoader(),
                new Class<?>[] { MCDataInput.class },
                (proxy, method, arguments) -> {
                    switch (method.getName()) {
                        case "readUByte":
                            return (short) data.readUnsignedByte();
                        case "readUShort":
                            return data.readUnsignedShort();
                        case "readInt":
                            return data.readInt();
                        default:
                            throw new AssertionError("Unexpected read method: " + method.getName());
                    }
                });
    }

    @Test
    void generatesAndCachesSlottedTileClass() {
        int traitId = MultipartMixinFactory.getId(TSlottedTile.class.getName().replace('.', '/'));
        assertFalse(traitId < 0);

        BitSet traits = new BitSet();
        traits.set(traitId);
        Object first = MultipartMixinFactory.construct(traits, Nil$.MODULE$);
        Object second = MultipartMixinFactory.construct(traits, Nil$.MODULE$);

        assertTrue(first instanceof TileMultipart);
        assertTrue(first instanceof TSlottedTile);
        assertNotSame(first, second);
        assertSame(first.getClass(), second.getClass());
        assertEquals(27, ((TSlottedTile) first).v_partMap().length);
    }
}
