package codechicken.multipart.test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNotSame;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.lang.reflect.Proxy;
import java.util.Arrays;
import java.util.BitSet;
import java.util.Collections;
import java.util.Set;
import java.util.TreeSet;

import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.server.MinecraftServer;

import org.junit.jupiter.api.Test;

import codechicken.lib.data.MCDataInput;
import codechicken.lib.data.MCDataOutput;
import codechicken.lib.data.MCDataOutputWrapper;
import codechicken.lib.vec.Cuboid6;
import codechicken.microblock.FaceMicroClass$;
import codechicken.microblock.HollowMicroClass$;
import codechicken.microblock.Microblock;
import codechicken.microblock.MicroblockGenerator;
import codechicken.multipart.JPartialOcclusion;
import codechicken.multipart.MultiPartRegistry;
import codechicken.multipart.MultipartHelper;
import codechicken.multipart.TFacePart;
import codechicken.multipart.TMultiPart;
import codechicken.multipart.TileMultipart;
import codechicken.multipart.asm.MultipartMixinFactory;
import codechicken.multipart.scalatraits.TSlottedTile;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Loader;
import scala.collection.JavaConversions;
import scala.collection.Seq;
import scala.collection.immutable.Nil$;

class ForgeEnvironmentSmokeTest {

    @Test
    void reachesServerStartedWithWorldAndMultipartModsLoaded() {
        assertTrue(ForgeMultipartFunctionalTestMod.preInitialized);
        assertTrue(ForgeMultipartFunctionalTestMod.initialized);
        assertTrue(ForgeMultipartFunctionalTestMod.postInitialized);
        assertTrue(ForgeMultipartFunctionalTestMod.serverAboutToStart);
        assertTrue(ForgeMultipartFunctionalTestMod.serverStarted);
        assertTrue(FMLCommonHandler.instance().getSide().isServer());
        assertTrue(Loader.isModLoaded("ForgeMultipart"));
        assertTrue(Loader.isModLoaded("ForgeMicroblock"));
        assertTrue(Loader.isModLoaded("McMultipart"));

        MinecraftServer server = MinecraftServer.getServer();
        assertNotNull(server);
        assertNotNull(server.worldServers);
        assertTrue(server.worldServers.length > 0);
        assertNotNull(server.worldServers[0]);
    }

    /**
     * Microblock classes are generated by ASM at runtime. TFacePart's members are now Java interface defaults rather
     * than Scala trait forwarders, so a generated class inherits them instead of declaring its own; this checks the JVM
     * resolves them for a class that never existed at compile time.
     */
    @Test
    void generatedMicroblockInheritsFacePartDefaults() {
        Microblock face = MicroblockGenerator.create(FaceMicroClass$.MODULE$, 0, false);
        Microblock hollow = MicroblockGenerator.create(HollowMicroClass$.MODULE$, 0, false);

        assertTrue(face instanceof TFacePart);
        assertEquals(0, ((TFacePart) face).redstoneConductionMap());

        // HollowMicroblock overrides both members, so its generated class must not pick up the defaults.
        assertTrue(hollow instanceof TFacePart);
        assertEquals(0x10, ((TFacePart) hollow).redstoneConductionMap());
        assertFalse(((TFacePart) hollow).solid(0));
    }

    @Test
    void generatedMicroblockInitializesAndDispatchesAnExternalScalaTrait() throws Exception {
        BitSet traits = new BitSet();
        traits.set(FaceMicroClass$.MODULE$.baseTraitId());
        traits.set(ForgeMultipartFunctionalTestMod.externalScalaMicroblockTraitId);
        Seq<Object> arguments = JavaConversions.asScalaBuffer(Collections.<Object>singletonList(0)).toList();

        Microblock microblock = (Microblock) MicroblockGenerator.construct(traits, arguments);
        Class<?> trait = Class.forName("codechicken.multipart.test.ExternalScalaMicroblockFixture");

        assertTrue(trait.isInterface());
        assertTrue(trait.isInstance(microblock));
        assertTrue(microblock.shouldRenderDynamic());
        assertEquals(41, microblock.getLightValue());
        assertEquals(41, ((Number) microblock.getClass().getMethod("fixtureState").invoke(microblock)).intValue());
    }

    /**
     * Part registration needs FML's active mod container, so none of this is reachable from a plain JVM test. Startup
     * exercises both overloads downstream depends on: Content registers through the deprecated IPartFactory array form,
     * and each microblock class registers through the IPartFactory2 varargs form.
     */
    @Test
    void registryResolvesPartsRegisteredThroughBothFactoryOverloads() throws Exception {
        assertTrue(MultiPartRegistry.loaded(), "Registration must be closed once the server has started");

        // mc_torch comes from the deprecated IPartFactory array overload.
        TMultiPart torch = MultiPartRegistry.loadPart("mc_torch", null);
        assertNotNull(torch);
        assertEquals("mc_torch", torch.getType());

        // mcr_face comes from the IPartFactory2 varargs overload. Its factory reads the tag, so it needs a real one;
        // an absent material name resolves to the missing-material placeholder rather than failing.
        TMultiPart face = MultiPartRegistry.loadPart("mcr_face", new NBTTagCompound());
        assertNotNull(face);
        assertEquals("mcr_face", face.getType());

        assertNotNull(MultiPartRegistry.getModContainer("mc_torch"));
        assertNotNull(MultiPartRegistry.getModContainer("mcr_face"));
    }

    @Test
    void partIdsRoundTripThroughTheRegistryCarrier() {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        MCDataOutput output = new MCDataOutputWrapper(new DataOutputStream(bytes));
        TMultiPart torch = MultiPartRegistry.loadPart("mc_torch", null);
        MultiPartRegistry.writePartID(output, torch);

        TMultiPart read = MultiPartRegistry.readPart(input(bytes.toByteArray()));

        assertNotNull(read);
        assertEquals("mc_torch", read.getType());
    }

    /** CodeChickenLib has no stream-backed MCDataInput, so the carrier reads are proxied. */
    private static MCDataInput input(byte[] bytes) {
        DataInputStream data = new DataInputStream(new ByteArrayInputStream(bytes));
        return (MCDataInput) Proxy.newProxyInstance(
                MCDataInput.class.getClassLoader(),
                new Class<?>[] { MCDataInput.class },
                (proxy, method, arguments) -> {
                    switch (method.getName()) {
                        case "readUByte":
                            return (short) data.readUnsignedByte();
                        case "readUShort":
                            return data.readUnsignedShort();
                        case "readInt":
                            return data.readInt();
                        default:
                            throw new AssertionError("Unexpected read method: " + method.getName());
                    }
                });
    }

    @Test
    void generatesAndCachesSlottedTileClass() throws Exception {
        int traitId = MultipartMixinFactory.getId(TSlottedTile.class.getName().replace('.', '/'));
        assertFalse(traitId < 0);

        BitSet traits = new BitSet();
        traits.set(traitId);
        Object first = MultipartMixinFactory.construct(traits, Nil$.MODULE$);
        Object second = MultipartMixinFactory.construct(traits, Nil$.MODULE$);
        Class<?> trait = Class.forName("codechicken.multipart.scalatraits.TSlottedTile");

        assertTrue(first instanceof TileMultipart);
        assertTrue(first instanceof TSlottedTile);
        assertTrue(trait.isInterface());
        assertNotSame(first, second);
        assertSame(first.getClass(), second.getClass());
        assertEquals(0, trait.getDeclaredFields().length);
        Set<String> signatures = new TreeSet<>();
        for (java.lang.reflect.Method method : trait.getDeclaredMethods()) {
            signatures.add(method.getName() + org.objectweb.asm.Type.getMethodDescriptor(method));
        }
        assertEquals(
                new TreeSet<>(
                        Arrays.asList(
                                "bindPart(Lcodechicken/multipart/TMultiPart;)V",
                                "canAddPart(Lcodechicken/multipart/TMultiPart;)Z",
                                "clearParts()V",
                                "codechicken$multipart$scalatraits$TSlottedTile$$super$bindPart"
                                        + "(Lcodechicken/multipart/TMultiPart;)V",
                                "codechicken$multipart$scalatraits$TSlottedTile$$super$canAddPart"
                                        + "(Lcodechicken/multipart/TMultiPart;)Z",
                                "codechicken$multipart$scalatraits$TSlottedTile$$super$clearParts()V",
                                "codechicken$multipart$scalatraits$TSlottedTile$$super$copyFrom"
                                        + "(Lcodechicken/multipart/TileMultipart;)V",
                                "codechicken$multipart$scalatraits$TSlottedTile$$super$partRemoved"
                                        + "(Lcodechicken/multipart/TMultiPart;I)V",
                                "copyFrom(Lcodechicken/multipart/TileMultipart;)V",
                                "partMap(I)Lcodechicken/multipart/TMultiPart;",
                                "partRemoved(Lcodechicken/multipart/TMultiPart;I)V",
                                "v_partMap()[Lcodechicken/multipart/TMultiPart;",
                                "v_partMap_$eq([Lcodechicken/multipart/TMultiPart;)V")),
                signatures);

        TMultiPart[] firstMap = (TMultiPart[]) trait.getMethod("v_partMap").invoke(first);
        TMultiPart[] secondMap = (TMultiPart[]) trait.getMethod("v_partMap").invoke(second);
        assertEquals(27, firstMap.length);
        assertEquals(27, secondMap.length);
        assertNotSame(firstMap, secondMap, "Each generated tile must run the trait initializer");
        assertEquals(TMultiPart[].class, first.getClass().getDeclaredField("v_partMap").getType());

        TMultiPart[] replacement = new TMultiPart[27];
        trait.getMethod("v_partMap_$eq", TMultiPart[].class).invoke(first, (Object) replacement);
        assertSame(replacement, trait.getMethod("v_partMap").invoke(first));
    }

    @Test
    void generatedJavaTraitOverridesPartialOcclusion() throws Exception {
        PartialPart existing = new PartialPart(voxel(0));
        TileMultipart tile = MultipartHelper.createTileFromParts(Collections.singletonList(existing));
        TileMultipart second = MultipartHelper
                .createTileFromParts(Collections.singletonList(new PartialPart(voxel(2))));
        Class<?> trait = Class.forName("codechicken.multipart.scalatraits.TPartialOcclusionTile");

        assertTrue(trait.isInterface(), "The registered Java mixin class is rewritten to a trait interface");
        assertTrue(trait.isInstance(tile));
        assertSame(tile.getClass(), second.getClass(), "The Java trait combination must keep using the class cache");
        assertEquals(0, trait.getDeclaredFields().length);
        Set<String> signatures = new TreeSet<>();
        for (java.lang.reflect.Method method : trait.getDeclaredMethods()) {
            signatures.add(method.getName() + org.objectweb.asm.Type.getMethodDescriptor(method));
        }
        assertEquals(
                new TreeSet<>(
                        Arrays.asList(
                                "codechicken$multipart$scalatraits$TPartialOcclusionTile$$super$occlusionTest"
                                        + "(Lscala/collection/Seq;Lcodechicken/multipart/TMultiPart;)Z",
                                "occlusionTest(Lscala/collection/Seq;Lcodechicken/multipart/TMultiPart;)Z",
                                "partialOcclusionTest(Lscala/collection/Seq;)Z")),
                signatures);
        assertEquals(
                boolean.class,
                tile.getClass().getMethod("partialOcclusionTest", scala.collection.Seq.class).getReturnType());
        assertTrue(tile.canAddPart(new PartialPart(voxel(1))));
        assertFalse(tile.canAddPart(new PartialPart(voxel(0))));
    }

    @Test
    void generatedServerPassThroughDelegatesCopiesAndAllowsOnlyOneImplementor() throws Exception {
        PassThroughPart part = new PassThroughPart();
        TileMultipart tile = MultipartHelper.createTileFromParts(Collections.singletonList(part));

        assertTrue(tile instanceof GeneratorPassThroughFixture);
        GeneratorPassThroughFixture api = (GeneratorPassThroughFixture) tile;
        assertEquals(12, api.transform(5));
        assertEquals("part:value", api.transform("value"));
        assertSame(part, api.implementation());
        assertFalse(tile.canAddPart(new PassThroughPart()));

        TileMultipart copy = (TileMultipart) tile.getClass().getDeclaredConstructor().newInstance();
        copy.from(tile);
        assertSame(part, ((GeneratorPassThroughFixture) copy).implementation());
        assertSame(copy, part.tile());

        copy.partRemoved(part, 0);
        assertTrue(copy.canAddPart(new PassThroughPart()), "Removing the delegate must clear the generated impl field");
    }

    private static Cuboid6 voxel(int x) {
        return new Cuboid6(x / 8d, 0, 0, (x + 1) / 8d, 1 / 8d, 1 / 8d);
    }

    private static final class PartialPart extends TMultiPart implements JPartialOcclusion {

        private final Cuboid6 box;

        private PartialPart(Cuboid6 box) {
            this.box = box;
        }

        @Override
        public String getType() {
            return "partial_fixture";
        }

        @Override
        public Iterable<Cuboid6> getPartialOcclusionBoxes() {
            return Collections.singletonList(box);
        }
    }

    private static final class PassThroughPart extends TMultiPart implements GeneratorPassThroughFixture {

        @Override
        public String getType() {
            return "pass_through_fixture";
        }

        @Override
        public int transform(int value) {
            return value + 7;
        }

        @Override
        public String transform(String value) {
            return "part:" + value;
        }

        @Override
        public TMultiPart implementation() {
            return this;
        }
    }
}
