// Add your dependencies here

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.11.4"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    functionalTestImplementation(platform("org.junit:junit-bom:5.11.4"))
    functionalTestImplementation("org.junit.jupiter:junit-jupiter")
    functionalTestImplementation("org.junit.platform:junit-platform-engine")
    functionalTestImplementation("org.junit.platform:junit-platform-launcher")
    functionalTestImplementation("org.junit.platform:junit-platform-reporting")

    implementation("com.github.GTNewHorizons:CodeChickenCore:1.4.12:dev")
    compileOnly("com.github.GTNewHorizons:Angelica:2.1.19:dev")
    compileOnly("com.github.GTNewHorizons:Postea:1.2.5:dev") {transitive = false}
    devOnlyNonPublishable("com.github.GTNewHorizons:NotEnoughItems:2.8.93-GTNH:dev") {
        exclude group: 'com.github.GTNewHorizons', module: 'CodeChickenCore'
    }
}
