package codechicken.multipart;

/**
 * Normal occlusion for parts that also extend {@link TMultiPart}.
 * <p>
 * A superclass method beats an interface default on the JVM, so implementors must override occlusionTest themselves
 * with {@code NormalOcclusionTest.apply(this, npart) && super.occlusionTest(npart)}, as {@link NormallyOccludedPart}
 * does. Declaring it default here would silently lose to TMultiPart's version.
 */
public interface TNormalOcclusion extends JNormalOcclusion {

    boolean occlusionTest(TMultiPart npart);

    /**
     * Super accessor generated by Scala for classes compiled against the original trait, called by
     * {@link TNormalOcclusion$class#occlusionTest}. Those classes supply their own override carrying their real super
     * chain; the default here is the identity for that chain and is only reached if the deprecated bridge is used on a
     * class that never had one.
     */
    default boolean codechicken$multipart$TNormalOcclusion$$super$occlusionTest(TMultiPart npart) {
        return true;
    }
}
